### ISSUE TITLE
what pdbx package does parse_cif_noX.py expect?

### ISSUE THREAD

**Issue by cseed** [dauparas/ProteinMPNN#105]
I'm trying to fine-tune ProteinMPNN but I'm unable to run parse_cif_noX.py to prepare my data for training.  In particular, it imports pdbx, but I can't find a suitable pdbx package.  I tried:

https://pypi.org/project/mmcif-pdbx/

but the import structure and method names don't match those used by parse_cif_noX.py.  Can you advise what pdbx package parse_cif_noX.py expects?  I couldn't find a mention of it in the docs.  Thanks!

**Comment by JoshuaMeyers** [comment]
I believe this should work: https://pypi.org/project/pdbx-mmcif/

**Comment by halasadi** [comment]
> I believe this should work: https://pypi.org/project/pdbx-mmcif/

Thanks @JoshuaMeyers ! I tried giving this pdbx a go, but I get this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datadrive/anaconda3/envs/pdbprocessing/lib/python3.7/site-packages/pdbx/reader/PdbxReader.py", line 72, in read
    self.__parser(self.__tokenizer(self.__ifh), containerList)
  File "/datadrive/anaconda3/envs/pdbprocessing/lib/python3.7/site-packages/pdbx/reader/PdbxReader.py", line 209, in __parser
    curCatName, curAttName, curQuotedString, curWord = next(tokenizer)
RuntimeError: generator raised StopIteration`

Maybe I am doing something wrong here. Are you able run this type of code without error?

`from pdbx.reader.PdbxReader import PdbxReader
from pdbx.reader.PdbxContainers import *
ifh = open("example.cif")
pRd = PdbxReader(ifh)
data = []
pRd.read(data)`

**Comment by anar-rzayev** [comment]
But does it still work? Because I have pip installed this package but `parse_cif_noX.py` still doesn't work

**Comment by maxshen29** [comment]
I'm facing the same problem. Has anyone solved this problem?

**Comment by JoshuaMeyers** [comment]
This hint is helpful https://github.com/dauparas/ProteinMPNN/issues/54#issuecomment-2324941638
