### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'inputs/*pdb' .How do fix this bug?

### ISSUE THREAD

**Issue by DragonReed** [dauparas/ProteinMPNN#49]
Traceback (most recent call last):
  File "E:\GitHub\ProteinMPNN\protein_mpnn_run.py", line 466, in <module>
    main(args)
  File "E:\GitHub\ProteinMPNN\protein_mpnn_run.py", line 162, in main
    pdb_dict_list = parse_PDB(args.pdb_path, ca_only=args.ca_only)
  File "E:\GitHub\ProteinMPNN\protein_mpnn_utils.py", line 166, in parse_PDB
    xyz, seq = parse_PDB_biounits(biounit, atoms=sidechain_atoms, chain=letter)
  File "E:\GitHub\ProteinMPNN\protein_mpnn_utils.py", line 85, in parse_PDB_biounits
    for line in open(x,"rb"):
OSError: [Errno 22] Invalid argument: 'inputs/*pdb'

**Comment by dauparas** [comment]
You can only pass one PDB path as an input when using `--pdb_path` option.
